//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeCharge.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeCharge.Resources.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to calendar.
        /// </summary>
        internal static string AddToCalendar {
            get {
                return ResourceManager.GetString("AddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Slot.
        /// </summary>
        internal static string AvailableSlot {
            get {
                return ResourceManager.GetString("AvailableSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Again.
        /// </summary>
        internal static string BookAgain {
            get {
                return ResourceManager.GetString("BookAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Expired.
        /// </summary>
        internal static string BookingExpired {
            get {
                return ResourceManager.GetString("BookingExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking ID: #0193741_NSW.
        /// </summary>
        internal static string BookingId {
            get {
                return ResourceManager.GetString("BookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Bookings.
        /// </summary>
        internal static string BookingSummary {
            get {
                return ResourceManager.GetString("BookingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Space.
        /// </summary>
        internal static string BookSpace {
            get {
                return ResourceManager.GetString("BookSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Booking.
        /// </summary>
        internal static string CancelBooking {
            get {
                return ResourceManager.GetString("CancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string CancelError {
            get {
                return ResourceManager.GetString("CancelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to cancel this booking? This can’t be undone..
        /// </summary>
        internal static string CancelPopupError {
            get {
                return ResourceManager.GetString("CancelPopupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-set maximum charge cost.
        /// </summary>
        internal static string ChargeCost {
            get {
                return ResourceManager.GetString("ChargeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged so far.
        /// </summary>
        internal static string ChargedSoFar {
            get {
                return ResourceManager.GetString("ChargedSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request charge estimate.
        /// </summary>
        internal static string ChargeEstimate {
            get {
                return ResourceManager.GetString("ChargeEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge is progress.
        /// </summary>
        internal static string ChargeInProgress {
            get {
                return ResourceManager.GetString("ChargeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger Type.
        /// </summary>
        internal static string ChargerType {
            get {
                return ResourceManager.GetString("ChargerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge speed.
        /// </summary>
        internal static string ChargeSpeed {
            get {
                return ResourceManager.GetString("ChargeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to charge.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Fee.
        /// </summary>
        internal static string ChargingFee {
            get {
                return ResourceManager.GetString("ChargingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 134.6 kW / $86.50.
        /// </summary>
        internal static string ChargingRate {
            get {
                return ResourceManager.GetString("ChargingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Summary.
        /// </summary>
        internal static string ChargingSummary {
            get {
                return ResourceManager.GetString("ChargingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        internal static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Support.
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Booking.
        /// </summary>
        internal static string ContinueBooking {
            get {
                return ResourceManager.GetString("ContinueBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Charging.
        /// </summary>
        internal static string ContinueCharging_ {
            get {
                return ResourceManager.GetString("ContinueCharging ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Required :.
        /// </summary>
        internal static string EnergyRequired {
            get {
                return ResourceManager.GetString("EnergyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event added to calender.
        /// </summary>
        internal static string EventAdded {
            get {
                return ResourceManager.GetString("EventAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Charging Location.
        /// </summary>
        internal static string FindaChargingLocation {
            get {
                return ResourceManager.GetString("FindaChargingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries, we&apos;ll send you a mail regarding resetting the password.
        /// </summary>
        internal static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        internal static string GetDirections {
            get {
                return ResourceManager.GetString("GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to you want to go back?.
        /// </summary>
        internal static string GoBackPrompt {
            get {
                return ResourceManager.GetString("GoBackPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Home.
        /// </summary>
        internal static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve arrived at your 2 p.m slot charge at Westfield Bondi Junction.
        /// </summary>
        internal static string JunctionArrivingMessage {
            get {
                return ResourceManager.GetString("JunctionArrivingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Booking.
        /// </summary>
        internal static string KeepBooking {
            get {
                return ResourceManager.GetString("KeepBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Charge.
        /// </summary>
        internal static string LastCharge {
            get {
                return ResourceManager.GetString("LastCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Plate.
        /// </summary>
        internal static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        internal static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find you.
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We need access to your location.
        ///To provide you with the best experience, our app requires access to your device&apos;s location..
        /// </summary>
        internal static string LocationErrorPopupText {
            get {
                return ResourceManager.GetString("LocationErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent Successfully!.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you a mail regarding resetting your password. Please reset the password and login again.
        /// </summary>
        internal static string MailSentMessage {
            get {
                return ResourceManager.GetString("MailSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make New Booking.
        /// </summary>
        internal static string MakeNewBooking {
            get {
                return ResourceManager.GetString("MakeNewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        internal static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary this month.
        /// </summary>
        internal static string MonthlySummary {
            get {
                return ResourceManager.GetString("MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help? Call us Now.
        /// </summary>
        internal static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, but it appears that you are currently not connected to the internet. Please check your network connection and try again..
        /// </summary>
        internal static string NetworkErrorPopupText {
            get {
                return ResourceManager.GetString("NetworkErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection!.
        /// </summary>
        internal static string no_internet_alert {
            get {
                return ResourceManager.GetString("no_internet_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending booking.
        /// </summary>
        internal static string NoPendingBooking {
            get {
                return ResourceManager.GetString("NoPendingBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous booking.
        /// </summary>
        internal static string NoPreviousBooking {
            get {
                return ResourceManager.GetString("NoPreviousBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upcoming booking.
        /// </summary>
        internal static string NoUpcomingBooking {
            get {
                return ResourceManager.GetString("NoUpcomingBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Amount.
        /// </summary>
        internal static string OtherAmount {
            get {
                return ResourceManager.GetString("OtherAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please park in Bay 3 to start charge.
        /// </summary>
        internal static string ParkInBay {
            get {
                return ResourceManager.GetString("ParkInBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Booking.
        /// </summary>
        internal static string PendingBooking {
            get {
                return ResourceManager.GetString("PendingBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your previous booking hasn&apos;t been confirmed yet. Kindly take a moment to finalize it..
        /// </summary>
        internal static string PendingBookingMessage {
            get {
                return ResourceManager.GetString("PendingBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-set maximum charge cost.
        /// </summary>
        internal static string PresetChargeCost {
            get {
                return ResourceManager.GetString("PresetChargeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Bookings.
        /// </summary>
        internal static string PreviousBookings {
            get {
                return ResourceManager.GetString("PreviousBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Personal details and Vehicle Information have been updated.
        /// </summary>
        internal static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Member? Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration submitted successfully.
        /// </summary>
        internal static string RegistrationSubmitted {
            get {
                return ResourceManager.GetString("RegistrationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration submitted successfully. Please check your email for instructions on what to do next..
        /// </summary>
        internal static string RegistrationSubmittedText {
            get {
                return ResourceManager.GetString("RegistrationSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining to limit.
        /// </summary>
        internal static string RemainingToLimit {
            get {
                return ResourceManager.GetString("RemainingToLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to home.
        /// </summary>
        internal static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Booking.
        /// </summary>
        internal static string ReviewBooking {
            get {
                return ResourceManager.GetString("ReviewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time to confirm this booking has expired. Please check slot availability again and re-try booking a space..
        /// </summary>
        internal static string SelectOtherSlot {
            get {
                return ResourceManager.GetString("SelectOtherSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charges.
        /// </summary>
        internal static string ServiceCharges {
            get {
                return ResourceManager.GetString("ServiceCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This slot is already booked.
        /// </summary>
        internal static string SlotAlreadyBooked {
            get {
                return ResourceManager.GetString("SlotAlreadyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortBy.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Charge.
        /// </summary>
        internal static string StartCharge {
            get {
                return ResourceManager.GetString("StartCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Charging.
        /// </summary>
        internal static string StartCharging {
            get {
                return ResourceManager.GetString("StartCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop charging?.
        /// </summary>
        internal static string StopChargePrompt {
            get {
                return ResourceManager.GetString("StopChargePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to stop charging? This can’t be undone..
        /// </summary>
        internal static string StopChargeWarning {
            get {
                return ResourceManager.GetString("StopChargeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Charging.
        /// </summary>
        internal static string StopCharging {
            get {
                return ResourceManager.GetString("StopCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time                      :.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost            :.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Consumed.
        /// </summary>
        internal static string UnitsConsumed {
            get {
                return ResourceManager.GetString("UnitsConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please wait a moment and try again as it may be a temporary issue. If this message persists, please contact support.
        /// </summary>
        internal static string UnknowErrorPopupText {
            get {
                return ResourceManager.GetString("UnknowErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Bookings.
        /// </summary>
        internal static string UpcomingBookings {
            get {
                return ResourceManager.GetString("UpcomingBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Charge.
        /// </summary>
        internal static string UpComingCharge {
            get {
                return ResourceManager.GetString("UpComingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehical Information.
        /// </summary>
        internal static string VehicalInformation {
            get {
                return ResourceManager.GetString("VehicalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s charge.
        /// </summary>
        internal static string VehicleCharge {
            get {
                return ResourceManager.GetString("VehicleCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note these are all estimates and can vary from vehicle to vehicle.
        /// </summary>
        internal static string VehicleCostNote {
            get {
                return ResourceManager.GetString("VehicleCostNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Vehicle is currently charging.
        /// </summary>
        internal static string VehicleCurrentlyCharging {
            get {
                return ResourceManager.GetString("VehicleCurrentlyCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Booking.
        /// </summary>
        internal static string ViewBooking {
            get {
                return ResourceManager.GetString("ViewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeCharge.
        /// </summary>
        internal static string WeCharge {
            get {
                return ResourceManager.GetString("WeCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry..
        /// </summary>
        internal static string WeChargeDescription {
            get {
                return ResourceManager.GetString("WeChargeDescription", resourceCulture);
            }
        }
    }
}
